version: '2'
services:
    dns:
        image: andyshinn/dnsmasq:2.75
        ports:
            - "53:53"
            - "53:53/udp"
        cap_add:
            - NET_ADMIN
        volumes:
            - ./services/dnsmasq/config/dnsmasq.conf:/etc/dnsmasq.conf
            - ./services/dnsmasq/config/resolv.dnsmasq:/etc/resolv.dnsmasq
    gogs:
        image: gogs/gogs
        ports:
            - "10022:22"
        volumes:
            - ./data/gogs/:/data
    web:
        image: nginx:1.11.1
        ports:
            - "80:80"
        depends_on:
            - php
        volumes_from:
            - php
        volumes:
            - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./services/nginx/config/sites-enabled:/etc/nginx/sites-enabled
            - ./data/nginx/logs/:/var/log/nginx/
        links:
            - gogs
    php:
        build:
            context: ./services/php
            dockerfile: Dockerfile
        volumes:
            - ./app:/mnt/app
    mariadb:
        image: mariadb:10.1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "app"
            MYSQL_PASSWORD: "app"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./services/mariadb/config/:/etc/mysql/conf.d/
    redis:
        image: redis:3.2.1
        ports:
            - "6379:6379"

