version: '2'
services:
    dns:
        image: andyshinn/dnsmasq:2.75
        ports:
            - "53:53"
            - "53:53/udp"
        cap_add:
            - NET_ADMIN
        volumes:
            - ./services/dnsmasq/config/dnsmasq.conf:/etc/dnsmasq.conf
            - ./services/dnsmasq/config/resolv.dnsmasq:/etc/resolv.dnsmasq
    gogs:
        image: gogs/gogs
        ports:
            - "10022:22"
        volumes:
            - ./data/gogs/:/data
    web:
        image: nginx:1.11.1
        ports:
            - "80:80"
        depends_on:
            - php
            - tomcat
        volumes_from:
            - php
        volumes:
            - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./services/nginx/config/sites-enabled:/etc/nginx/sites-enabled
            - ./data/nginx/logs/:/var/log/nginx/
        links:
            - gogs
    php:
        build:
            context: ./services/php
            dockerfile: Dockerfile
        volumes:
            - ./app:/mnt/app
    tomcat:
        image: tomcat:8.0
        environment:
            CATALINA_BASE: "/usr/local/tomcat"
            CATALINA_HOME: "/usr/local/tomcat"
            CATALINA_TMPDIR: "/usr/local/tomcat/temp"
            JRE_HOME: "/usr"
            CLASSPATH: "/usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar"
        volumes:
            - ./services/tomcat/bin/startup.sh:/usr/local/tomcat/bin/startup.sh
            - ./services/tomcat/config/server.xml:/usr/local/tomcat/conf/server.xml
            - ./services/tomcat/config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
            - ./services/tomcat/config/logging.properties:/usr/local/tomcat/logging.properties
            - ./data/tomcat/logs/:/usr/local/tomcat/logs/
            - ./app/java-webapp/:/usr/local/tomcat/webapps/meaon/
    mariadb:
        image: mariadb:10.1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "app"
            MYSQL_PASSWORD: "app"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./services/mariadb/config/my.cnf:/etc/mysql/my.cnf
    redis:
        image: redis:3.2.1
        ports:
            - "6379:6379"
    console:
        build:
            context: ./services/console
            dockerfile: Dockerfile
        volumes_from:
            - php

